// autogenerated by scripts/create/create-metas.js
import { Category } from 'hint/dist/src/lib/enums/category';
import { HintScope } from 'hint/dist/src/lib/enums/hint-scope';
import { HintMetadata } from 'hint/dist/src/lib/types';

import { getMessage } from '../i18n.import';

const meta: HintMetadata = {
    docs: {
        category: Category.accessibility,
        description: getMessage('keyboard_description', 'en'),
        name: getMessage('keyboard_name', 'en')
    },
    /* istanbul ignore next */
    getDescription(language: string) {
        return getMessage('keyboard_description', language);
    },
    /* istanbul ignore next */
    getName(language: string) {
        return getMessage('keyboard_name', language);
    },
    id: 'axe/keyboard',
    schema: [{
        additionalProperties: false,
        properties: {
            accesskeys: { enum: ['off', 'warning', 'error'], type: 'string' },
            bypass: { enum: ['off', 'warning', 'error'], type: 'string' },
            'focus-order-semantics': { enum: ['off', 'warning', 'error'], type: 'string' },
            region: { enum: ['off', 'warning', 'error'], type: 'string' },
            'skip-link': { enum: ['off', 'warning', 'error'], type: 'string' },
            tabindex: { enum: ['off', 'warning', 'error'], type: 'string' }
        }
    }],
    scope: HintScope.any
};

export default meta;
