// autogenerated by scripts/create/create-metas.js
import { Category } from 'hint/dist/src/lib/enums/category';
import { HintScope } from 'hint/dist/src/lib/enums/hint-scope';
import { HintMetadata } from 'hint/dist/src/lib/types';

import { getMessage } from '../i18n.import';

const meta: HintMetadata = {
    docs: {
        category: Category.accessibility,
        description: getMessage('structure_description', 'en'),
        name: getMessage('structure_name', 'en')
    },
    /* istanbul ignore next */
    getDescription(language: string) {
        return getMessage('structure_description', language);
    },
    /* istanbul ignore next */
    getName(language: string) {
        return getMessage('structure_name', language);
    },
    id: 'axe/structure',
    schema: [{
        additionalProperties: false,
        properties: {
            'css-orientation-lock': { enum: ['off', 'warning', 'error'], type: 'string' },
            'definition-list': { enum: ['off', 'warning', 'error'], type: 'string' },
            dlitem: { enum: ['off', 'warning', 'error'], type: 'string' },
            'frame-tested': { enum: ['off', 'warning', 'error'], type: 'string' },
            'hidden-content': { enum: ['off', 'warning', 'error'], type: 'string' },
            list: { enum: ['off', 'warning', 'error'], type: 'string' },
            listitem: { enum: ['off', 'warning', 'error'], type: 'string' }
        }
    }],
    scope: HintScope.any
};

export default meta;
