// autogenerated by scripts/create/create-hints.js
import { HintContext } from 'hint/dist/src/lib/hint-context';
import { IHint } from 'hint/dist/src/lib/types';
import { register } from './util/axe';

import meta from './meta/forms';

export default class AxeHint implements IHint {
    public static readonly meta = meta;
    public constructor(context: HintContext) {
        register(context, ['autocomplete-valid', 'checkboxgroup', 'form-field-multiple-labels', 'label', 'label-title-only', 'radiogroup'], ['checkboxgroup', 'label-title-only', 'radiogroup']);
    }
}
