// autogenerated by scripts/create/create-hints.js
module.exports = {
    aria: require('./aria'),
    color: require('./color'),
    forms: require('./forms'),
    keyboard: require('./keyboard'),
    language: require('./language'),
    'name-role-value': require('./name-role-value'),
    other: require('./other'),
    parsing: require('./parsing'),
    semantics: require('./semantics'),
    'sensory-and-visual-cues': require('./sensory-and-visual-cues'),
    structure: require('./structure'),
    tables: require('./tables'),
    'text-alternatives': require('./text-alternatives'),
    'time-and-media': require('./time-and-media')
};
