// autogenerated by scripts/create/create-hints.js
import { HintContext } from 'hint/dist/src/lib/hint-context';
import { IHint } from 'hint/dist/src/lib/types';
import { register } from './util/axe';

import meta from './meta/keyboard';

export default class AxeHint implements IHint {
    public static readonly meta = meta;
    public constructor(context: HintContext) {
        register(context, ['accesskeys', 'bypass', 'focus-order-semantics', 'region', 'skip-link', 'tabindex'], ['accesskeys', 'focus-order-semantics', 'region', 'skip-link', 'tabindex']);
    }
}
