// autogenerated by scripts/create/create-metas.js
module.exports = {
    aria: require('./meta/aria'),
    color: require('./meta/color'),
    forms: require('./meta/forms'),
    keyboard: require('./meta/keyboard'),
    language: require('./meta/language'),
    'name-role-value': require('./meta/name-role-value'),
    other: require('./meta/other'),
    parsing: require('./meta/parsing'),
    semantics: require('./meta/semantics'),
    'sensory-and-visual-cues': require('./meta/sensory-and-visual-cues'),
    structure: require('./meta/structure'),
    tables: require('./meta/tables'),
    'text-alternatives': require('./meta/text-alternatives'),
    'time-and-media': require('./meta/time-and-media')
};
