// autogenerated by scripts/create/create-hints.js
import { HintContext } from 'hint/dist/src/lib/hint-context';
import { IHint } from 'hint/dist/src/lib/types';
import { register } from './util/axe';

import meta from './meta/structure';

export default class AxeHint implements IHint {
    public static readonly meta = meta;
    public constructor(context: HintContext) {
        register(context, ['css-orientation-lock', 'definition-list', 'dlitem', 'frame-tested', 'hidden-content', 'list', 'listitem'], ['css-orientation-lock', 'frame-tested', 'hidden-content']);
    }
}
