// autogenerated by scripts/create/create-hints.js
import { HintContext } from 'hint/dist/src/lib/hint-context';
import { IHint } from 'hint/dist/src/lib/types';
import { register } from './util/axe';

import meta from './meta/text-alternatives';

export default class AxeHint implements IHint {
    public static readonly meta = meta;
    public constructor(context: HintContext) {
        register(context, ['area-alt', 'document-title', 'frame-title', 'frame-title-unique', 'image-alt', 'image-redundant-alt', 'input-image-alt', 'object-alt', 'role-img-alt', 'server-side-image-map', 'video-caption', 'video-description'], ['frame-title-unique', 'image-redundant-alt']);
    }
}
