const fs = require('fs');
const path = require('path');

const cwd = process.cwd();

// Generate i18n.import.ts
const i18nFile = path.join(cwd, 'src', '_locales', 'en', 'messages.json');

const messages = require(i18nFile);
const filename = path.join(cwd, 'src', 'i18n.import.ts');
const content = `// autogenerated by scripts/create-i18n.js
import { getMessage as getMessageGlobal, GetMessageOptions } from '@hint/utils/dist/src/i18n/get-message';

export type MessageName =
${
    Object.keys(messages).map((name) => {
        return `    '${name}'`;
    })
        .join(' |\n')
};

export const getMessage = (message: MessageName, options?: GetMessageOptions) => {
    return getMessageGlobal(message, options);
};
`;

fs.writeFile(filename, content, (err) => {
    if (err) {
        throw err;
    } else {
        console.log(`Created: ${filename} `);
    }
});
