const fs = require('fs');
const path = require('path');
const pkg = require('../package.json');

const parserModules = Object.keys(pkg.devDependencies).filter((name) => {
    return name.startsWith('@hint/parser-');
});

// Generate parsers.import.ts

const parsersPath = path.resolve(`${__dirname}/../src/shared/parsers.import.ts`);
const parsers = `// autogenerated by scripts/import-parsers.js

import { IParserConstructor } from 'hint/dist/src/lib/types';

const parsers: Map<string, IParserConstructor> = new Map([
${
    parserModules.map((name) => {
        return `    ['${name.split('-')[1]}', require('${name}').default]`;
    }).join(',\n')
}
]);

export default parsers;
`;

fs.writeFile(parsersPath, parsers, (err) => {
    if (err) {
        throw err;
    } else {
        console.log(`Created: ${parsersPath}`);
    }
});
